### ISSUE TITLE
Notification sound no processing

### ISSUE THREAD

**Issue by leho6694** [Zackptg5/Notification-Helper-Remover#1]
Hi,i have pocophone F1,miui 10.0.6 android 8.1. if I am not mistaken, your mod should help me, but unfortunately it does not work. I have installed v4a FX 1.8.1 from magisk. And it's working, but when I listen music the notification sound it's not processing by v4a. You mod not help me, maybe you have any solution?

**Comment by Zackptg5** [comment]
Did you install aml? It's required in your scenario since both this mod and v4a modify the same files (audio_effects)

**Comment by leho6694** [comment]
You mean audio modification library? Yes. maybe the order of the installation makes a difference? I installed v4a first, then notification helper, then aml, that was mistake?

**Comment by Zackptg5** [comment]
Ya, order doesn't matter either. What exactly do you mean by notification sound isn't processing? Can you attach your vendor audio_effects?

**Comment by leho6694** [comment]
v4a status in settings all is working, I set master gate> output -40, and all sound in phone quietly, but when I turn on the music in the player, the music is still quiet but the voice of notifications, the voice of the touch, louder. Sry4 my English

**Comment by leho6694** [comment]
I dont think it`s a v4a configuration issue, I use viper long time on my xperia m2. I played with the settings in v4a, nothing changes that. the volume of the touch changes only when I listen to music. Until I turn on the music, all sounds are silent, including notifications and touch sound
[audio_effects.zip](https://github.com/Zackptg5/Notification-Helper-Remover/files/2627100/audio_effects.zip)

**Comment by Zackptg5** [comment]
Try deleting: /vendor/lib/soundfx/libvolumelistener.so
Note that v4a may process everything after doing this

**Comment by leho6694** [comment]
I can't delete this file, after trying he is still on soundfx,I use mixplorer,es file manager

**Comment by Zackptg5** [comment]
Delete it in twrp, or at /sbin/.core/mirror/vendor/lib/soundfx
