### ISSUE TITLE
how to revert back to original settings?

### ISSUE THREAD

**Issue by wokawoka** [Zackptg5/Notification-Helper-Remover#2]
Hello, thank you very much for sharing this nice module.
Just a question, how to revert back to the original settings?
Would just uninstalling it from magisk enough?
Thanks again

**Comment by Zackptg5** [comment]
Just flash the zip again and it'll uninstall it (removing it with magisk is fine too). In the future, use the support thread for questions (I'll add it to the readme): https://forum.xda-developers.com/android/software-hacking/mods-zackptg5-s-misc-projects-t3881164

**Comment by wokawoka** [comment]
Thanks for replying and for pointing out the support thread (I couldn't find it on the description in the magisk repo nor in the readme on github, and I even searched for it on google but missed it).
